### ISSUE TITLE
v0.9.0-201506031622

### ISSUE THREAD

**Issue by dyh** [ElijahLabs/AudioBible#1]
- 选择完书卷，未选择章的时候，请不要播放。
- 未开始播放时，切换上一章按钮、下一章按钮、以及选择书卷列表和章节列表，自动播放了。这里请不要播放。
- 请在程序打开时，自动切换到上一次关闭的章。
- [1.起初，  神创造天地。]， 请改为[1空格空格起初，  神创造天地。]，1后面的句号改为二个半角空格。

**Comment by yz89** [comment]
* “选择章”改成相应的书卷名
* 选择书卷时不要切换经文

**Comment by dyh** [comment]
- 选择创世记第50章后，再选择出埃及记，章的列表会固定在第40章。请定位到章列表中的第1章。

**Comment by yz89** [comment]
* 选择章改成相应的书卷名
* 选择书卷时不要切换经文

**Comment by yz89** [comment]
以上问题已修正，现关闭
