### ISSUE TITLE
v0.9.0-201506041830

### ISSUE THREAD

**Issue by dyh** [ElijahLabs/AudioBible#2]
- 手动点击下一章，从创世记点到路得记第1章的时候，点击下一章按钮不好用了。
- 手动点击上一章，从创世记点到马太福音第1章的时候，点击上一章按钮不好用了。
- 播放创世记第1章时，手动卷动到第31节，点击左上角【书卷】，选择第2章，经文界面停留在20-25小节，这里请卷动到第1节。
- 播放创世记第2章，关闭程序，再次启动程序，点击播放按钮，会显示第2章的经文，播放第1章的音频。

**Comment by Paulyoufu** [comment]
1     在左边栏切换章节时，经文不在第1节显示 也就是滚动条不在顶上 ，（这块需要调用SCROLLTOP那个接口）
2  约书亚3章11节没有经文
3  约书亚记 21章 10节 没有经文
4 申命记 4章33节 没有经文
5申命记 13章13节 18节 没有经文
6申命记 30章10节  没有经文
7 士师记 20章28节 没有经文
8 撒母耳记下 3章10没有经文
9历代志上 4章18    16章13节 16章40节没有经文

**Comment by yz89** [comment]
没有经文 的是正常现象。不用统计

**Comment by Paulyoufu** [comment]
10 士师记5章  1节 经文 是那时   语音是那时候
11 撒母记上 第14章 1 经文是有一日 ，语音是有一天
历代志上 22 章1节 语音没有直是第2节
12 约伯记 10章 往后下一章 语音不切换 也不能停

**Comment by Paulyoufu** [comment]
12 条取消 重启又好用了
